version: "3"
services:
    app-db:
        container_name: app-db
        image: postgres:13-alpine
        hostname: app-db
        volumes:
            - ./volume_data/app-db:/var/lib/postgresql/data
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=school_user
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=school
    dashboard-db:
        container_name: dashboard-db
        image: postgres:13-alpine
        hostname: dashboard-db
        volumes:
            - ./volume_data/dashboard-db:/var/lib/postgresql/data
        restart: always
        ports:
            - "5431:5432"
        environment:
            - POSTGRES_USER=dashboard_user
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=dashboard
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        hostname: pgadmin
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=secret
            - PGADMIN_LISTEN_PORT=5433
        ports:
            - "5433:5433"
        volumes:
            - ./volume_data/pgadmin:/var/lib/pgadmin
        links:
            - "app-db:app-pgsql-server"
            - "dashboard-db:dashboard-pgsql-server"
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        volumes:
            - ./volume_data/rabbitmq/etc/:/etc/rabbitmq/
            - ./volume_data/rabbitmq/data/:/var/lib/rabbitmq/
            - ./volume_data/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672