CREATE TABLE IF NOT EXISTS OUTBOX_MESSAGE(
	ID BIGSERIAL,
	CLASS_NAME VARCHAR(500),
	OPERATION VARCHAR(200),
	TOPIC VARCHAR(200),
	PAYLOAD TEXT,
	PROCESSED_AT TIMESTAMP,
	PROCESSED BOOLEAN NOT NULL DEFAULT FALSE,
	ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
	LAST_MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_OUTBOX_MESSAGE PRIMARY KEY(ID)
);