CREATE SCHEMA IF NOT EXISTS SCHOOL;

CREATE TABLE IF NOT EXISTS TEACHER(
	ID BIGSERIAL,
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	EMAIL VARCHAR(200) UNIQUE,
	ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
	LAST_MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_TEACHER PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS STUDENT(
	ID BIGSERIAL,
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	CLASS VARCHAR(5) NOT NULL,
	GRADE INT NOT NULL DEFAULT 1,
	FOREIGN_LANGUAGE_TEACHER_ID BIGINT,
	FOREIGN_LANGUAGE VARCHAR(200),
	ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
	LAST_MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_STUDENT PRIMARY KEY(ID),
	CONSTRAINT FK_FOREIGN_LANGUAGE_TEACHER FOREIGN KEY(FOREIGN_LANGUAGE_TEACHER_ID) REFERENCES TEACHER(ID)
);

CREATE INDEX FOREIGN_LANGUAGE_TEACHER_IDX ON STUDENT (FOREIGN_LANGUAGE_TEACHER_ID);