CREATE TABLE IF NOT EXISTS REVINFO (
	REV BIGSERIAL NOT NULL,
	REVTSTMP BIGINT,
	CONSTRAINT PK_REVINFO PRIMARY KEY(REV)
);

CREATE TABLE IF NOT EXISTS TEACHER_AUD(
	ID BIGINT NOT NULL,
	REV BIGINT NOT NULL,
    REVTYPE SMALLINT,
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	EMAIL VARCHAR(200),
	ACTIVE BOOLEAN,
	LAST_MODIFIED TIMESTAMP,
	CREATED_AT TIMESTAMP,
	CONSTRAINT PK_TEACHER_AUD PRIMARY KEY(ID, REV)
);

CREATE TABLE IF NOT EXISTS STUDENT_AUD(
	ID BIGINT,
	REV BIGINT,
    REVTYPE SMALLINT,
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	CLASS VARCHAR(5),
	GRADE INT,
	FOREIGN_LANGUAGE_TEACHER_ID BIGINT,
	FOREIGN_LANGUAGE VARCHAR(200),
	ACTIVE BOOLEAN,
	LAST_MODIFIED TIMESTAMP,
	CREATED_AT TIMESTAMP,
	CONSTRAINT PK_STUDENT_AUD PRIMARY KEY(ID, REV)
);

CREATE TABLE IF NOT EXISTS OUTBOX_MESSAGE_AUD(
	ID BIGINT NOT NULL,
	REV BIGINT NOT NULL,
    REVTYPE SMALLINT,
	CLASS_NAME VARCHAR(500),
	OPERATION VARCHAR(200),
	TOPIC VARCHAR(500),
	KEY VARCHAR(100),
	PAYLOAD TEXT,
	PROCESSED_AT TIMESTAMP,
	PROCESSED BOOLEAN,
	ACTIVE BOOLEAN,
	LAST_MODIFIED TIMESTAMP,
	CREATED_AT TIMESTAMP,
	CONSTRAINT PK_OUTBOX_MESSAGE_AUD PRIMARY KEY(ID, REV)
);

ALTER TABLE TEACHER_AUD 
ADD CONSTRAINT FK_REV_TEACHER_AUD 
FOREIGN KEY (REV) 
REFERENCES REVINFO(REV);

ALTER TABLE STUDENT_AUD 
ADD CONSTRAINT FK_REV_STUDENT_AUD 
FOREIGN KEY (REV) 
REFERENCES REVINFO(REV);

ALTER TABLE OUTBOX_MESSAGE_AUD 
ADD CONSTRAINT FK_REV_OUTBOX_MESSAGE_AUD 
FOREIGN KEY (REV) 
REFERENCES REVINFO(REV);